- Gemfile.lock
- app/assets/stylesheets/_button.scss
- app/assets/stylesheets/_footer.scss
- app/assets/stylesheets/_header.scss
- app/assets/stylesheets/_masthead.scss
- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/posts/edit.html.erb
- app/views/posts/new.html.erb
- app/views/projects/new.html.erb
@tvararu Please double check the Gemfile lock changes, which add arm64.
| Home | Post |
|--|--|
|![localhost_3000_projects_1_posts_new (1)](https://user-images.githubusercontent.com/319055/197415789-93cc71b1-ee57-4b3c-9f38-efc3ab07b84c.png) | ![localhost_3000_projects_1_posts_new](https://user-images.githubusercontent.com/319055/197415792-02eeee81-52e4-49a4-81da-22105dc9fbe2.png) |
> Add custom header, footer and button styles

- app/controllers/posts_controller.rb
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/models/user.rb
- db/migrate/20221025210636_add_user_to_project.rb
- db/schema.rb
Also that users can't edit projects/create posts/edit posts unless they belong to them.
> Ensure projects belong to users

- README.md
- app/controllers/pages_controller.rb
- app/views/pages/working.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/routes.rb
> Add initial subdomain support

- app/helpers/application_helper.rb
- app/views/posts/index.html.erb
> Add design history link to admin posts index

- app/assets/stylesheets/_header.scss
- app/models/project.rb
- app/views/app/index.html.erb
- config/locales/validations.en.yml
- db/migrate/20221111092302_add_index_to_projects.rb
- db/schema.rb
Add the masthead, missing header border-bottom, and posts heading.
The content is a bit weird for the design history design history, lol.
> Design History
> Design History
> Design History design history
> How the design of the Design History service has changed
> Better subdomain validations and index masthead

- app/controllers/posts_controller.rb
- app/views/posts/_form.html.erb
- app/views/posts/show.html.erb
Also set up mimetypes to only accept png/jpeg.
> Accept multiple images when uploading files

- app/assets/stylesheets/_upload-screenshots.scss
- app/assets/stylesheets/application.scss
- app/views/posts/_form.html.erb
> Add app-upload-screenshots styles

- app/views/posts/_form.html.erb
See https://github.com/design-history/design-history/pull/48#discussion_r1020590614
> Add gif support to image upload

- app/assets/stylesheets/_button.scss
- app/assets/stylesheets/_upload.scss
- app/controllers/posts_controller.rb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/posts/_form.html.erb
- app/views/projects/_form.html.erb
> Add button to delete attachments

- app/controllers/posts_controller.rb
- app/models/post.rb
- app/views/posts/index.html.erb
Follow the design from the prototype.
> Separate draft and published posts in admin index

- app/controllers/application_controller.rb
> Remove basic auth

- app/assets/stylesheets/application.scss
- app/views/pages/landing.html.erb
> Landing fixes

- Gemfile
- Gemfile.lock
- app/controllers/app_controller.rb
- app/controllers/posts_controller.rb
- app/models/post.rb
- app/views/app/index.html.erb
- app/views/posts/_form.html.erb
- config/initializers/friendly_id.rb
- db/migrate/20221122235501_make_post_slugs_unique.rb
- db/migrate/20221122235825_create_friendly_id_slugs.rb
- db/schema.rb
- test/fixtures/posts.yml
> Configure slugs via friendly_id

- app/assets/stylesheets/_footer.scss
- app/views/layouts/base.html.erb
Link to the Design History design history, and to the source code.
> Add footer links

- app/views/layouts/_header.html.erb
> Add header link to "Your design histories"

- app/controllers/post_images_controller.rb
Forgot to add a filter when I added friendly IDs.
> Fix image upload

- spec/rails_helper.rb
- spec/system/design_histories_spec.rb
- spec/system/posts_spec.rb
- spec/system/projects_spec.rb
- spec/system/teams_spec.rb
Ignore google fonts and refactor some of the specs.
> Minor test improvements

- config/locales/validations.en.yml
> Add missing validations for AddUserForm

- app/controllers/app_controller.rb
- app/controllers/manage_access_controller.rb
- app/controllers/pages_controller.rb
- app/models/project.rb
- app/views/pages/robots.text.erb
- config/routes.rb
- public/robots.txt
- spec/system/password_protection_spec.rb
It blocks attempts to crawl on non-production environments, as well as on private projects.
> Add robots.txt route

- app/controllers/app_controller.rb
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/layouts/app.html.erb
- app/views/layouts/base.html.erb
- app/views/projects/_form.html.erb
- config/locales/validations.en.yml
- db/migrate/20221203203137_add_theme_to_projects.rb
- db/schema.rb
- spec/factories/projects.rb
Just an intermediary design to allow us to play around with the feature.
> Allow specifying a theme when editing a project

- config/initializers/govuk_markdown.rb
- spec/system/design_histories_spec.rb
This transforms quotes and dashes into their "smart" typographic variants.
> Add SmartyPants to govuk_markdown

- app/assets/stylesheets/_masthead.scss
- app/components/app_masthead_component.html.erb
- app/components/app_masthead_component.rb
- app/views/app/index.html.erb
- app/views/pages/landing.html.erb
- app/views/pages/start.html.erb
Rename it to `AppMastheadComponent` and refactor some of the CSS.
> Refactor masthead component

- app/assets/stylesheets/_summary-card.scss
- app/assets/stylesheets/application.scss
- app/components/app_summary_card_component.html.erb
- app/components/app_summary_card_component.rb
- app/components/app_summary_card_header_component.html.erb
- app/components/app_summary_card_header_component.rb
Based on the XGovukSummaryCardComponent.
> Add AppSummaryCardComponent

- app/controllers/posts_controller.rb
- app/views/posts/index.html.erb
> Update posts list design to use summary and table

- .github/workflows/lint.yml
- .github/workflows/test.yml
This allows contributors with forks to run actions.
> Update github actions to run on pull_requests

- app/assets/stylesheets/_header.scss
- app/assets/stylesheets/_masthead.scss
- app/components/app_masthead_component.html.erb
- app/views/pages/start.html.erb
| Before | After |
|--|--|
| ![localhost_3000_start (1)](https://user-images.githubusercontent.com/319055/214347407-5624e844-89ba-4ea6-8535-a42ab4d53576.png) | ![localhost_3000_start](https://user-images.githubusercontent.com/319055/214347415-7d49e5a6-45d6-45e9-8b92-3e0a37f8c045.png) |
| ![localtest app local_3000_ (1)](https://user-images.githubusercontent.com/319055/214347427-68731bc3-b3f9-473d-97cb-b80da6543760.png) | ![localtest app local_3000_](https://user-images.githubusercontent.com/319055/214347428-1a5b5da5-72ae-4b86-bc39-dbcfaad324d6.png) |
> Bring header and masthead styles inline with prototype

- app/views/shared/_screenshots.html.erb
- Add contents list when more than 1 screenshot
- Put screenshots heading within section
- Add ID to section
- Use image ID to link to images
> Add a contents list of screenshots

- app/assets/stylesheets/_related-links.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/dh.scss
- app/views/app/show.html.erb
Was missed in https://github.com/design-history/design-history/pull/169.
> Add related links styling

- app/helpers/application_helper.rb
- app/views/posts/index.html.erb
- Use friendly text for the design history link
- Hide posts table when there are no posts
- Show description in the summary card
> Project page iteration

- app/models/post.rb
It's reasonable to have a post with:
- a descriptive title
- a bunch of screenshots
- an empty body
> Allow posts without a body

- app/models/project.rb
- spec/system/projects_spec.rb
Users might paste in a full domain, we should:
- remove any protocols
- strip anything after the first `.` in the domain
Fixes #197
> Be more accepting when collecting subdomain

- app/models/post.rb
- app/views/posts/_form.html.erb
- spec/system/posts_spec.rb
Create an automatic slug based on the title given
"This title" becomes "this-title"
Fixes #159
> Generate slugs from titles

- app/assets/stylesheets/_posts.scss
- app/views/app/index.html.erb
Reduce spacing between title and date.
> Clean up styling of post lists on index page

- app/views/post_images/index.html.erb
- spec/system/screenshots_spec.rb
> Rename button to "Add images"

- app/controllers/post_images_controller.rb
- app/helpers/application_helper.rb
- app/views/post_images/index.html.erb
- app/views/shared/_screenshots.html.erb
- spec/system/screenshots_spec.rb
Will do the same for captions if this is approved.
> Add alt text

- app/assets/stylesheets/_screenshots.scss
- app/views/post_images/index.html.erb
- Add caption styling
- Improve focus styles for screenshots
- Remove rendered caption from screenshots tab (we only need the input here)
> Caption styling

- app/views/post_images/index.html.erb
- app/views/posts/edit.html.erb
- spec/system/posts_spec.rb
- Keep titles consistent between tabs
- Put title and action into <title> tag
- Indicate if the post is draft or published
> Show the post being edited in the title

- app/controllers/application_controller.rb
- app/views/post_images/index.html.erb
- lib/tasks/update_spaces_access_control.rake
This should allow users to more easily embed images inline into their posts.
> Add markdown embed code to screenshots page

- config/environments/production.rb
Forgot to do this in the previous PR.
> Configure email host in production

- app/views/devise/passwords/edit.html.erb
This page was still using the default Devise design.
> Redesign change password page

- Gemfile
- Gemfile.lock
[Version 10 was yanked](https://github.com/ilyakatz/data-migrate/issues/267) so all CI builds are failing.
> Downgrade data_migrate

- Dockerfile
Missed in https://github.com/design-history/design-history/pull/403
> Bump node version in Dockerfile

- Dockerfile
This is needed to get the deploy to pass.
> Add libyaml-dev to docker build deps

- Gemfile
- Gemfile.lock
- config/initializers/devise.rb
- spec/factories/teams.rb
- spec/rails_helper.rb
- spec/system/teams_spec.rb
> Fix deprecation warnings

- spec/rails_helper.rb
This should fix some of the test timeouts on PRs.
> Bump Cuprite process_timeout

- app/views/pages/landing.html.erb
We've been getting weekly bot signups so the form has lost some of its usefulness.
> Remove waitlist
