design-history/design-history

app/javascript/controllers/auto_save_controller.js
app/javascript/controllers/index.js
app/views/posts/_form.html.erb

This implements a Stimulus controller that automatically saves the content of a form to localStorage, and reinstantiates it should the user navigate away and come back.
When the user submits the form, the local storage is cleared.
Based on https://stevepolito.design/blog/rails-auto-save-form-data/.

Autosave drafts on Post new and edit forms

---

app/controllers/projects_controller.rb
app/views/posts/index.html.erb
app/views/projects/_form.html.erb
app/views/projects/edit.html.erb
app/views/projects/index.html.erb
app/views/projects/new.html.erb

- Stop referring to histories as projects
- List histories with descriptions
- Move change link onto history page

Clean up new history and edit history flows

---

app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/pages/start.html.erb
config/locales/validations.en.yml

- Bring start page inline with prototype
- Create an account, not Sign up
- "Email address" label field
- Add missing page titles
- Adds friendlier error messages
- Show error summary before page title

Tweaks to sign up and sign in

---

app/controllers/app_controller.rb
app/controllers/pages_controller.rb
app/models/project.rb
app/views/app/index.html.erb
app/views/app/show.html.erb
app/views/pages/start.html.erb
app/views/pages/working.html.erb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/routes.rb

This adds a new controller for `designhistory.app` related routes, and namespaces the devise/other ones for the .io main domain. The index/show views still need to be customised to the latest version in the prototype, which is coming up as a follow-up.

Basic subdomain support

---

app/controllers/app_controller.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/routes.rb

Prefixing the domain with . means to allow all subdomains, and is more robust than driving this by the database.
[Rename main_domain to admin_domain](https://github.com/design-history/design-history/commit/a792e75b05b57ec25988c5c5b8f803974ef02eb7).
[Use find_by! for subdomain project lookup](https://github.com/design-history/design-history/commit/5a18fc0b1d2140fb969c39918c8bea334a8fa6a4). This allows the app to return a 404 if the matching project isn't found.

Allow arbitrary subdomains on admin and app domain 

---

app/assets/stylesheets/_upload-screenshots.scss
app/assets/stylesheets/_upload.scss
app/assets/stylesheets/application.scss
app/controllers/posts_controller.rb
app/views/posts/_form.html.erb
app/views/posts/edit.html.erb
app/views/posts/index.html.erb
config/application.rb

See commits for more details:
- Link to posts edit directly from index
- Don't replace existing images when adding new ones
- Use tabs on the edit post page
- Customise form labels on post edit page
- Display uploaded images when editing posts
- Redirect to edit post after editing a post
The design is different from the prototype; this is the no-JS version that will progressively enhance into the full green dropzone one from the prototype, and combine that with Ajax upload.
What's pretty high priority now is reordering/removing images, and the alt text/caption editor.

Display uploaded images when editing posts

---

app/assets/stylesheets/_button.scss
app/views/posts/index.html.erb
app/views/projects/_form.html.erb
app/views/projects/index.html.erb

The previous CSS refactor from overriding `govuk-button` to creating new `app-button` styles left out a few buttons.
I had to override `govuk-button--start` stlyes because our helper doesn't allow customising classes. Tech debt.

Fix some more buttons

---

app/assets/stylesheets/_upload.scss
app/controllers/post_images_controller.rb
app/controllers/posts_controller.rb
app/models/post.rb
app/views/app/show.html.erb
app/views/posts/_form.html.erb
app/views/posts/show.html.erb
config/application.rb
config/routes.rb
db/migrate/20221116180342_add_ordered_image_ids_to_posts.rb
db/schema.rb
lib/array_element_move.rb
test/fixtures/posts.yml

Best reviewed commit by commit and ignoring whitespace.
Also use a turbo frame to handle image uploads, deletion, and reordering, which honestly feels like magic.

Add buttons to reorder post images

---

app/controllers/posts_controller.rb
app/views/posts/_form.html.erb
app/views/posts/show.html.erb

While building the last version of the image upload feature, post creation broke because adding images now requires an existing post. This temporarily disables adding images while writing the initial draft.

Fix post creation

---

config/initializers/inflections.rb

We don't want filenames with keywords like UK to end up as Uk after being humanized.

Configure inflector to not downcase some acronyms

---

app/controllers/app_controller.rb
app/controllers/manage_access_controller.rb
app/controllers/projects_controller.rb
app/models/project.rb
app/views/app/password.html.erb
app/views/manage_access/edit.html.erb
app/views/posts/index.html.erb
app/views/projects/edit.html.erb
config/locales/validations.en.yml
config/routes.rb
db/migrate/20221126205618_add_password_to_projects.rb
db/schema.rb
spec/factories/posts.rb
spec/factories/projects.rb
spec/factories/users.rb
spec/system/password_protection_spec.rb

Note that the password field is set as a regular text field, both on the settings, and on the user confirmation page. This is intentional; I think because it's not an especially secure method of authentication, it makes sense to not hide it.

Add password protection feature

---

app/controllers/teams_controller.rb
app/forms/add_user_form.rb
app/models/team.rb
app/models/user.rb
app/views/manage_access/edit.html.erb
app/views/teams/_form.html.erb
app/views/teams/new.html.erb
app/views/teams/show.html.erb
config/locales/validations.en.yml
config/routes.rb
db/migrate/20221127153056_create_teams.rb
db/migrate/20221127153423_add_team_to_users.rb
db/schema.rb
spec/factories/teams.rb
spec/factories/users.rb
spec/system/teams_spec.rb

This branch was getting a bit too large, so I decided to merge in incomplete teams support.
This adds a new section in "Manage access" that allows you to create a team. Once you do so, your user is then associated with that team. Users can currently only be associated to one team at a time.
The teams show page has a form that allows you to invite other users to your team. This functionality is currently quite simplistic, and requires you to type in the user's exact email address, and they need to already have an account and to not be part of a team. So, it's enough for our own use, but requires a bit of refinement to be production-ready.
Follow-up PRs will contain things such as:
- Allow users to edit design histories belonging to their team
- Refine the UI, make it a bit nicer even if …

Incomplete teams support

---

Gemfile
Gemfile.lock
app/controllers/projects_controller.rb
app/models/project.rb
app/models/user.rb
db/data/20221128223253_use_owner_on_projects.rb
db/data_schema.rb
db/migrate/20221128224537_add_owner_to_projects.rb
db/schema.rb
lib/tasks/fly.rake
spec/factories/projects.rb
spec/system/design_histories_spec.rb
spec/system/password_protection_spec.rb
spec/system/posts_spec.rb
spec/system/teams_spec.rb

Sets up a new `owner` reference from projects to users, which allows us to make projects belong to either a user, or a team. Also migrates existing user references, and updates tests accordingly.
Removing the user reference will be done as a follow-up; this needs to deploy fully as a prerequisite.

Add owner to projects

---

app/controllers/projects_controller.rb
app/models/project.rb
app/models/user.rb
db/data/20221128223253_use_owner_on_projects.rb
db/data_schema.rb
db/schema.rb
spec/system/design_histories_spec.rb
spec/system/password_protection_spec.rb
spec/system/posts_spec.rb
spec/system/teams_spec.rb

This reverts commit f341326a060ffb14ba50f5e27d6656b51541c505.
Now that the deploy has succeeded, and the schema is up to date, we can ship the data migration.

Revert "Revert "Add owner association on projects""

---

app/controllers/projects_controller.rb
app/models/project.rb
db/migrate/20221128230116_remove_user_from_projects.rb
db/migrate/20221128230901_set_owner_not_null_on_projects.rb
db/schema.rb
spec/factories/projects.rb
spec/system/design_histories_spec.rb
spec/system/password_protection_spec.rb
spec/system/posts_spec.rb
spec/system/teams_spec.rb

Completes the migration to the new owner field, and makes the owner columns not nullable to prevent orphaned projects from occurring.

Replace user with owner on projects

---

app/assets/stylesheets/_header.scss
app/assets/stylesheets/_masthead.scss
app/assets/stylesheets/_upload.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/dh.scss
app/assets/stylesheets/gov.scss
app/assets/stylesheets/nhs.scss
app/assets/stylesheets/themes.txt
app/views/layouts/base.html.erb
package.json

Ensure they are compiled by the sass command. Adds a `themes.txt` which is meant to contain the Sass input/output arguments.
Also extracts some more variables from various components that need to look different depending on the theme.
| Theme | Password | Index | Show |
| - | - | - | - |
| Design history | ![image](https://user-images.githubusercontent.com/1650875/205460247-a945db7a-496a-444f-8a93-c1d261ae0218.png) | ![image](https://user-images.githubusercontent.com/1650875/205460284-ff512170-948c-4591-9858-d641639e7bce.png) | ![image](https://user-images.githubusercontent.com/1650875/205460290-b7ae302e-0d0c-4d04-a3f5-4da90f5514f2.png) |
| Government | ![image](https://user-images.githubusercontent.com/1650875/205460317-e5a4101c-82d1-43d1-9360-97d195b5e46f.png) | …

Add stylesheets for dh/gov/nhs themes

---

Gemfile.lock

Allows setup on an M2 MacBook.

Add ARM64 Darwin 22 architecture

---

app/helpers/application_helper.rb
app/views/posts/index.html.erb

Update the index to the new design from the prototype.
Posts are coming up in a follow-up piece.

Display design history details using summary card

---

app/views/layouts/base.html.erb

Consolidate the two links next to the copyright notice.
I've decided to keep the source code link in the page, as it's something I personally tend to look for when I'm using other websites.
Fixes #151.

Update footer design

---

app/views/layouts/base.html.erb

Using a paragraph element renders the footer font larger (19px) than intended (16px). Following convention used on other sites that use `govuk-frontend`, use a `div` and give it a class of `govuk-footer__meta-custom` (which while not necessary, adds a margin below which may be useful if further content is added later, and also follows the conventions used elsewhere).
(Not sure if `govuk-components` has a slot for this, I think it’s pretty much the Wild West when it comes to the footer component!)

Correct font size for footer text

---

app/controllers/manage_access_controller.rb

Without this, a user that attempts to access the edit page and isn't signed in will encounter a 500, as per this Sentry error: https://sentry.io/organizations/design-history/issues/3887506917/?project=4504255433539584

Authenticate users for manage access controller

---

app/assets/stylesheets/_global.scss

This is implemented as a global rule because it's a pretty specific element and it's unlikely to clash with other 3rd party rules.
Styles stolen from GOV.UK.

Add blockquote styling

---

config/initializers/session_store.rb

After a user has given a password for a private design history, we don't really want to be asking again.

Increase cookie length to 1 year

---

app/models/post.rb
app/views/app/show.html.erb
app/views/posts/_form.html.erb
db/migrate/20230125113130_set_default_on_post_related_links.rb
db/schema.rb
spec/factories/posts.rb

- Add missing aria markup from https://github.com/design-history/design-history/pull/171/files#r1086515043
- Change database default to `''`
- Rename it to "Related content" in the view
- Don't display the related links section unless it's present

Fix related links bugs

---

app/controllers/projects_controller.rb
app/models/project.rb
app/views/app/index.html.erb
app/views/projects/_form.html.erb
db/migrate/20230125131201_add_related_links_to_projects.rb
db/schema.rb
spec/factories/projects.rb
spec/system/related_links_spec.rb

Allows users to add a related content sidebar to design histories that shows up on the home page.
Closes  #161.

Add related links to projects

---

app/views/projects/_form.html.erb

The class wasn't intentional. Also update the hint text.
See https://github.com/design-history/design-history/pull/175#discussion_r1086702164.

Update hint for project related links

---

app/models/post.rb
config/locales/validations.en.yml

Without this, entering a duplicate slug violates an uniqueness constraint on the DB and throws a 500 error.
Not sure whether the content is 👍  or 👎 .

Validate that post slugs are unique to the project

---

app/controllers/post_images_controller.rb
app/controllers/posts_controller.rb
app/controllers/teams_controller.rb
app/views/layouts/_banners.html.erb
app/views/layouts/base.html.erb
app/views/posts/edit.html.erb
app/views/projects/index.html.erb
config/routes.rb
spec/system/posts_spec.rb
spec/system/projects_spec.rb

Fixes #196 by putting a Sign in link in the footer of the design history and adding a `/sign-in` slug
Fixes #192 and fixes #190 by removing the broken link and adding "View post" to success banner
Improves the new user journey

Design tweaks

---

app/assets/stylesheets/application.scss
app/models/post.rb
app/views/posts/index.html.erb

- When generating a slug, adhere to the 50 char max length
- Do not wrap date and actions in posts view
- Make new post button more obvious

Improvements to posts table and slug logic

---

app/helpers/application_helper.rb

Numbers can be used in filenames to determine ordering before uploading.
- Remove any numbering at the beginning of the filename
- Replace `-` with `_` for better humanizing

Better image title generation

---

Gemfile
Gemfile.lock
app/avo/resources/user_resource.rb
app/controllers/avo/users_controller.rb
app/models/user.rb
config/initializers/avo.rb
config/locales/avo.en.yml
config/locales/avo.fr.yml
config/locales/avo.nb.yml
config/locales/avo.nn.yml
config/locales/avo.pt-BR.yml
config/locales/avo.pt.yml
config/locales/avo.ro.yml
config/locales/avo.tr.yml
config/locales/pagy/nn.yml
config/locales/pagy/ro.yml
config/routes.rb
db/migrate/20230309180122_add_admin_to_users.rb
db/schema.rb
spec/factories/users.rb

This uses [Avo](https://avohq.io/) which is a modern admin panel for Rails apps. It has a free community licence which probably has enough features for our needs. More advanced features are available with a paid licence.
While it doesn't follow the design language or theme of the rest of the app, the fact that it comes pre-built and does all the CRUDy bits is pretty useful. It requires less development time to stand up and lets us perform back-office tasks without having to dip into a Rails console.
If this is good enough, we can add more doohickeys to it in a follow-up PR.
Navigate to `/avo` as an admin user, and click on `Users` in the sidebar:

Add an admin panel

---

app/controllers/post_images_controller.rb
app/helpers/application_helper.rb
app/views/post_images/index.html.erb
app/views/shared/_screenshots.html.erb
spec/system/screenshots_spec.rb

Images now have a Markdown-enabled caption field which shows up under images on the screenshot editing page and on the post page.

Add captions

---

app/avo/resources/project_resource.rb
app/controllers/avo/projects_controller.rb

This will allow us to gauge activity and see if design histories are being written by users.

Display projects in Avo admin

---

app/models/post.rb
app/views/posts/_form.html.erb
spec/system/posts_spec.rb

- Don't force users to enter a publish date
- Default to today
- Hide the publish date fields behind a details component

Default to today when publishing

---

app/views/posts/new.html.erb
spec/system/posts_spec.rb

Reduce this page to just a form asking for the Title. This way, users are less likely to be confused why the form is missing components such as the screenshots section.
Fixes #193.

Simplify "New post" page

---

app/controllers/post_images_controller.rb
app/models/post.rb
app/views/post_images/index.html.erb
config/application.rb
spec/system/screenshots_spec.rb

This is deprecated in Rails 7.1 and was coming up as a warning during our test run.
We can instead rely on the `.attach` method.
Based on https://stackoverflow.com/a/71990877

Remove replace_on_assign_to_many = false setting

---

app/controllers/posts_controller.rb
app/views/posts/_form.html.erb
config/locales/validations.en.yml
spec/system/posts_spec.rb

When users input invalid parameters to the published_at date fields, Rails picks these up as `published_at(1i)`, `published_at(2i)` and `published_at(3i)`. These then get passed directly to `.update`.
If any of these parameters are out of range, this triggers a multiparameter assignment error, which is a 500.
It isn't possible to guard for these in the model, because the field is of type date, and we can't create a valid date object from invalid parameters.
Because of this, we have to validate in the controller, which is a bit messy.

Handle error when users incorrectly enter published_at

---

config/storage.yml
lib/tasks/update_spaces_access_control.rake

Currently, images are private on DigitalOcean Spaces. This means that embedding them in posts requires generating a one-time URL with access controls.
Instead, we can make the images public by default, and migrate all existing images to public using a rake task.
Note that public isn't the same as enumerable/guessable, as File listing is still set to Restricted in the bucket settings. An example of a public image is this:
https://design-history.ams3.digitaloceanspaces.com/8x3eyop5d3xd0ea5uax11lwlzkrx
So anyone can see it as long as they have that URL. The URL does not have any auth cookie/credentials attached, and it never expires. But guessing that UUID at the end isn't possible, except if you view a post. This seems like a good trade-off for now, but we might consider adding "fully …

Set all images to public by default

---

app/avo/resources/comment_resource.rb
app/controllers/app_controller.rb
app/controllers/avo/comments_controller.rb
app/controllers/comments_controller.rb
app/controllers/projects_controller.rb
app/models/comment.rb
app/models/post.rb
app/models/project.rb
app/views/app/show.html.erb
app/views/projects/_form.html.erb
app/views/shared/_comments.html.erb
config/locales/validations.en.yml
config/routes.rb
db/migrate/20230427084754_create_comments.rb
db/migrate/20230427123444_add_comments_enabled_to_projects.rb
db/schema.rb
spec/factories/comments.rb
spec/factories/projects.rb
spec/system/comments_spec.rb

We've received feedback on one of our design histories that our colleagues would like to be able to comment on the individual posts.
This adds a commenting feature to public posts. The design is very similar to the one on the GOV.UK blog,
Notably absent:
- Support for threaded replies
- "Email me if someone replies to my comment"
- No animation / folding of input fields when initially loaded
There is a back-office interface to see and manage comments at `/avo/resources/comments`.
~~More important to consider is that there's no way to selectively turn off comments on certain posts, or to moderate them as an end user. Let's discuss here if we think we need the former at this stage as it's not much effort to make this feature opt-in by adding a flag on each post (or on a design history, …

Add initial support for comments

---

Dockerfile
app/services/spam_checker.rb

Without this, assets fail to precompile when building the docker image.
Also fix a typo in a comment.

Set OPENAI_ACCESS_TOKEN in Dockerfile

---

app/controllers/pages_controller.rb
app/views/devise/registrations/new.html.erb
app/views/layouts/base.html.erb
app/views/layouts/two-thirds.html.erb
app/views/pages/privacy_notice.md
app/views/shared/_comments.html.erb
config/routes.rb

This is a starter privacy notice for the service. Now that we're allowing comments, and those comments are processed by third parties (OpenAI), we should tell our users about this.

Add privacy notice

---

app/views/shared/_comments.html.erb

Without this, because this is in a turbo frame, clicking it results in "Content missing."

Add target="_top" to privacy notice link

---

app/views/layouts/base.html.erb

This was missed in the GOVUK Components 4.0.0 refactor.

Fix footer.meta call

---

app/controllers/posts_controller.rb
app/views/post_images/index.html.erb
app/views/posts/_form.html.erb
app/views/posts/edit.html.erb
app/views/posts/preview.html.erb
app/views/shared/_edit_post_header.html.erb
app/views/shared/_edit_post_tabs.html.erb
config/routes.rb
spec/system/preview_spec.rb

This adds a new "Preview" tab.
Because we need to save a version of the post in order to preview it, instead of adding the link to the tab headers, I decided to make it into a button on the actual form itself. That way it's hopefully more obvious to the user that saving a published post would immediately update the live one...
We should revisit the preview feature later with a more thorough data model, like actual post versions. However, until then, this should be a good stop-gap to help with previewing posts while writing them.
The tab "disappears" when you navigate back to the Write or Screenshots sections.

Add "Save and preview" button to post edit form

---

app/views/shared/_edit_post_header.html.erb

This was broken in https://github.com/design-history/design-history/pull/304/commits/f80a69f453c6273563b8fd33dbbeb7067803fd77#diff-005f7ad34f8f1c371fb65b6fb0dff00d3627a023bd4f06885809ce7cf20f8423R7
Fixes https://github.com/design-history/design-history/issues/317

Fix breadcrumb on post edit

---

fly.toml

Fly have updated their apps platform to v2. This is the result of running `fly config` and asking it to overwrite the existing one.

Migrate fly.toml

---

.tool-versions

Deploys are failing because `yarn` has been upgraded to 4.0.0 on CI which requires Node v18.12.0 or higher.

Bump node tool version

---

config/initializers/govuk_markdown_extension.rb
spec/initializers/govuk_markdown_spec.rb

If there are no headers specified, then the whole content of the email is assumed to be the body.

Make headers optional in email markdown

---

app/views/shared/_comments.html.erb

Smart quotes for smart people. 💅

Use ‘smart’ punctuation for apostrophe

---

app/controllers/teams_controller.rb
app/views/layouts/_header.html.erb
app/views/teams/_form.html.erb
app/views/teams/add_user.html.erb
app/views/teams/show.html.erb
config/routes.rb
spec/system/teams_spec.rb

This splits out the "Add new user" form to its own page and uses a design that's more similar to the one on the Design history show page.

Iterate team page design

---

app/helpers/application_helper.rb
app/views/app/show.html.erb

This looks better for posts with long titles.

Wrap post titles in two_thirds 

---

Gemfile
Gemfile.lock

The original ref has already been released.

Repoint the capybara dependency back to Rubygems

---

.dockerignore

This ensures that the log folder isn't removed when building the Docker image.
Deploys now succeed locally.

Add log/.keep to dockerignore

---

.github/workflows/deploy.yml

This ensures that multiple subsequent deploys don't clash into each other, and the last merged commit will win.

Cancel in progress deploys

---

Gemfile
Gemfile.lock

9.4.x isn't compatible with Rails 7.2.

Bump data-migrate

---

app/controllers/projects_controller.rb

These should be included as the design history template will automatically add them.

Export images that are shown at the bottom

---

app/javascript/controllers/govuk_accordion_controller.js
app/javascript/controllers/govuk_button_controller.js
app/javascript/controllers/govuk_character_count_controller.js
app/javascript/controllers/govuk_checkboxes_controller.js
app/javascript/controllers/govuk_error_summary_controller.js
app/javascript/controllers/govuk_header_controller.js
app/javascript/controllers/govuk_notification_banner_controller.js
app/javascript/controllers/govuk_radios_controller.js
app/javascript/controllers/govuk_skip_link_controller.js
app/javascript/controllers/govuk_tabs_controller.js

govuk-frontend removed the need to call .init.

Remove .init() calls from stimulus components
